name: Push Test
on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Modify file
        run: |
          echo "test $(date)" > test.txt

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add test.txt
          git commit -m "push test"

          git remote set-url origin https://${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git
          git push
